# Generated by Django 4.0.3 on 2022-04-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Next show')),
                ('city', models.CharField(choices=[('SF', 'San Francisco'), ('LA', 'Los Angeles'), ('SD', 'San Diego'), ('NY', 'New York')], default='SF', max_length=2, verbose_name='choose city')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
