# Generated by Django 4.0.3 on 2022-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='venue',
            field=models.ManyToManyField(to='main_app.venue'),
        ),
    ]
